config/routes.rb
Rails.application.routes.draw do

    resources :groups
    resources :contacts, only: [:new, :create, :destroy, :edit, :update, :show]
    root "contacts#index"
    get "contacts/find" => "contacts#find", as: :find_contact

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord

    belongs_to :group

    validates :telephone, presence: true
    validates :name, presence: true
    validates :email, presence: true
    validates :name, length: {minimum: 5}
end

app/models/group.rb
class Group < ApplicationRecord

    has_many :contact
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	before_action :set_contact, only: [:destroy, :edit, :update, :show]

	def index
		@contacts = Contact.includes(:group).order(:name)
	end

	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new contact_params
		if @contact.save
			flash[:notice] = "Contact was successfully created."
			redirect_to root_url
		else
			renderiza :new
		end
	end

	def edit
		renderiza :edit
	end

	def update
		if @contact.update contact_params
			flash[:notice] = "Contact was successfully updated."
			redirect_to root_url
		else
			renderiza :edit
		end
	end

	def destroy
		@contact.destroy
		redirect_to root_url
	end

	def show
		@group = Group.find(@contact.group_id)
	end

	private
	def set_contact
		@contact = Contact.find(params[:id])
	end

	def renderiza(view)
		@contacts = Contact.all
		render view
	end

	def contact_params
		params.require(:contact).permit(:name, :telephone, :email, :group_id)
	end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	before_action :set_group, only: [:show, :edit, :update, :destroy]

	def index
		@groups = Group.all
	end

	def show
	end

	def new
		@group = Group.new
	end

	def edit
	end

	def create
		@group = Group.new(group_params)

		if @group.save
			redirect_to groups_path
			flash[:notice] = 'Group was successfully created.'
		else
			render :new
		end
	end

	def update
		if @group.update(group_params)
			redirect_to groups_path
			flash[:notice] = 'Group was successfully updated.'
		else
			render :edit
		end
	end

	def destroy
		@group.destroy
		redirect_to groups_url
		flash[:notice] = 'Group was successfully destroyed.'
	end

	private
	def set_group
		@group = Group.find(params[:id])
	end

	def group_params
		params.require(:group).permit(:name)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/contacts/_contact.html.erb
<tbody>
	<tr class = "paciente">
		<td class = "info-nome"> <%= contact.name %></td>
		<td> <%= contact.group.name %></td>
		<td> <%= contact.email %></td>
		<td> <%= contact.telephone %></td>
		<td class = "col-md-1 col-md-offset-9"><%= link_to "Show",
			contact_path(contact), class: "btn btn-info"%>
		</td>
		<td class = "col-md-1 col-md-offset-10"><%= link_to "Edit",
			edit_contact_path(contact), class: "btn btn-warning"%>
		</td>
		<td class = "col-md-1 col-md-offset-11"><%= button_to "Delete", contact,
			method: :delete,
			class: "btn btn-danger",
				data: {confirm: "Are you sure that you remove #{contact.name}?"}%>
			</td>
		</tr>
	</tbody>

app/views/contacts/_form.html.erb
<%= form_for @contact do |f| %>
	<div class = "form-group">
		<%= f.label :name %>
		<%= f.text_field :name, class: "form-control" %>
	</div>

	<div class = "form-group">
		<%= f.label :telephone %>
		<%= f.text_field :telephone, class: "form-control"%>
	</div>

	<div class = "form-group">
		<%= f.label :email %>
		<%= f.text_field :email, class: "form-control"%>
	</div>

	<div class = "form-group">
		<%= f.label :group %>
		<%= f.collection_select :group_id, Group.all, :id, :name, {}, class: "form-control" %>
	</div>

	<div class = "form-group">
		<%= f.submit text_action, class: "btn btn-success col-md-2" %>
	</div>

<% end %>

<%= link_to "Back", root_path, class: "btn btn-default col-md-2 col-md-offset-1" %>

app/views/contacts/edit.html.erb
<div class = "col-md-5">
	<h1>Editing Contact</h1>

	<%= render partial: 'form', locals: {text_action: 'Edit'} %>
</div>

app/views/contacts/index.html.erb
<table class="table table-bordered">
	<thead>
		<tr>
			<th>Name</th>
			<th>Group</th>
			<th>Email</th>
			<th>Telephone</th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
	</thead>

	<%= render @contacts %>
</table>

</br>
<div class = "form-group">
	<%= link_to "New Contact", new_contact_path, class: "btn btn-success col-md-2 col-md-offset-7" %>
	<%= link_to "New Group", new_group_path, class: "btn btn-success col-md-2 col-md-offset-1" %>
</div>

app/views/contacts/new.html.erb
<div class = "col-md-5">
	<h1>New Contact</h1>

	<%= render partial: 'form', locals: {text_action: 'Create'} %>
</div>

app/views/contacts/show.html.erb
<h1><%= @contact.name %></h1>
<%= @contact.telephone %><br/>
<%= @contact.email %><br/>
<%= @group.name %>

app/views/groups/_form.html.erb
<%= form_for @group do |f| %>
<div class="form-group">
	<%= f.label :name %>
	<%= f.text_field :name, class: "form-control" %>
</div>

<div class="form-group">
	<%= f.submit text_action, class: "btn btn-success col-md-2" %>
</div>
<% end %>

<%= link_to 'Back', root_path, class: "btn btn-default col-md-2 col-md-offset-1" %>

app/views/groups/edit.html.erb
<div class = "col-md-5">
	<h1>Editing Group</h1>

	<%= render partial: 'form', locals: {text_action: 'Update'} %>
</div>

app/views/groups/index.html.erb
<h1>Group</h1>

<table class="table table-bordered">
	<thead>
		<tr>
			<th>Name</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @groups.each do |group| %>
		<tr>
			<td><%= group.name %></td>
			<td><%= link_to 'Edit', edit_group_path(group), class: "btn btn-warning"  %></td>
			<td><%= link_to 'Delete', group, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"  %></td>
		</tr>
		<% end %>
	</tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path, class: "btn btn-default" %>

app/views/groups/new.html.erb
<div class = "col-md-5">
	<h1>New Group</h1>

	<%= render partial: 'form', locals: {text_action: 'Create'} %>
</div>

app/views/layouts/_header.html.erb
<header>
	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<a href="#" class="navbar-brand">Phonebook</a>
			</div>
			<div id="navbarCollapse" class="collapse navbar-collapse">
				<ul class="nav navbar-nav navbar-right">
					<%= text_field_tag :name, @name, class: "form-control" %>
				</ul>
			</div>
		</div>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Phonebook</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="content">
	<%= render "layouts/header" %>

	<div class="container main-container">
		<div id="flash">
			<% flash.each do |key, value| %>
				<div class="alert alert-<%= key %>"><%= value %></div>
			<% end %>
		</div>
		<%= yield %>
	</div>
</body>
</html>